# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:20-slim

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source files
COPY . .

# Build TypeScript
RUN npm run build

# Clean up dev dependencies
RUN npm prune --production

# Run the server
CMD ["node", "dist/index.js"]
